@echo off
echo Starting deployment process...
echo 1. Staging changes...
git add .
echo 2. Committing changes...
git commit -m "Update website content"
echo 3. Pushing source code to main branch...
git push origin main
echo 4. Deploying public folder to GitHub Pages...
git subtree push --prefix public origin gh-pages
echo.
echo Deployment complete!
echo Please check https://danligairi1978.github.io/BBSwebsiteFJ/ in a few minutes.
pause
